# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/songguokunsgg"

[social.params]
icon = "brand-github"

[[social]]
identifier = "知乎"
name = "知乎"
url = "https://www.zhihu.com/people/yan-song-92-20"

[social.params]
icon = "brand-twitter"
